//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thuoc()
        {
            this.ChiTietDons = new HashSet<ChiTietDon>();
        }
    
        public int MaThuoc { get; set; }
        public string TenThuoc { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string DVT { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<int> MaDN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDon> ChiTietDons { get; set; }
        public virtual DonNhap DonNhap { get; set; }
        public virtual LoaiThuoc LoaiThuoc { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
